// ACTIONS FOR AUTHENTICATION/AUTHORIZATION
export const LOGIN = "LOGIN";
export const LOGOUT = "LOGOUT";
export const REGISTER = "REGISTER";
export const AUTH_ERROR = "AUTH_ERROR";
export const UPDATE_INFO_USERS = "UPDATE_INFO_USERS";
export const CLEAR_STATUS = "CLEAR_STATUS";

// ACTIONS FOR PRODUCT
export const GET_ALL_PRODUCT = "GET_ALL_PRODUCT";
export const GET_PRODUCT = "GET_PRODUCT";
export const CREATE_PRODUCT = "CREATE_PRODUCT";
export const UPDATE_PRODUCT = "UPDATE_PRODUCT";
export const DELETE_PRODUCT = "DELETE_PRODUCT";
export const PREVIEW_PRODUCT = "PREVIEW_PRODUCT";
export const CLEAR_PRODUCT = "CLEAR_PRODUCT";
export const CLEAR_ALL_PRODUCT = "CLEAR_ALL_PRODUCT";
export const CLEAR_STATUS_PRODUCT = "CLEAR_STATUS_PRODUCT";
export const PRODUCT_ERROR = "PRODUCT_ERROR";

// ACTIONS FOR TRANSACTION
export const GET_ALL_TRBUYER = "GET_ALL_TRBUYER";
export const GET_ALL_TRSELLER = "GET_ALL_TRSELLER";
export const CREATE_TRANSACTION = "CREATE_TRANSACTION";
export const UPDATE_TRANSACTION = "UPDATE_TRANSACTION";
